{
"stages": [{"name": "test"}, {"name": "deploy"}],
   "before_install" : "true",
   "env" : {
      "global" : {
         "secure" : "PL0CI6nxqVlz1sIjuliceAXI75QsOTdFAa4Fe956ftJqI/xV3gVtiLY8kIGE7fcjYqRj\u002BX6eWQ3yhkuOCRdaoH\u002Brms/kOivC3fLmD7QhKV9vcyN0yPPYAInaxg4ArcNjq5MIIcHbcgsLmjhtDJh/yGwRRk09ZHRhHYNzizA86E2Bys2\u002Bz8xNH13OCBI1/W0I6\u002Bf8QNzjJABsw4BJSVZjD2RVl13/kVro/6jdG9AvKG\u002BXTviZIXwX5Bnfqg0FkWVJaUMxQhFvORPPBWHWxVhRQqXfHcObF9lduhrhJU9O8EaGOl\u002BO/HWF2pVD78VZH2z8WPCxmrCB0l4j43tlmZGSAuKNOfRHTMzpzQKQTbGmVmzPfYrva\u002B1uEfEdIO3d9NZ2RTtAk\u002B9BPXKZ8ko/rqgOssj6ANQQ1MNHLBCreRgeOpsalsDF1gYU2TVnYuXItQ\u002BMQ3VmZeLzuqT0xCtDJOw8P8hbLk9sA25\u002BxHv1GSvmm6jsvpvkU18JnE9QO\u002B8MQQ7xWtMimBjOTaYrlZpjBcNyzeTeyj4bJPSw4IMy\u002BCZHepvN9RfUDEzqWA8utNGCXjicioknhXGJArNYazy54uM0rNGKpAX4XTPCG/ezztXUkxl58i3fVVe1WWsm1DRK87b6RSas4f4LSRabAnI7JAc\u002B5gJsaltLMz2ytWU5hx0Vjws="
      }
   },
   "git" : {
      "submodules" : false
   },
   "install" : "make test-deps",
   "jobs" : {
      "include" : [
         {
            "before_install" : "true",
            "install" : "true",
            "script" : "curl -f https://gist.githubusercontent.com/wakaba/ab553f86cd017e0cb28c6dbb5364b009/raw/travis-merge-job.pl | perl",
            "stage" : "merge"
         }
      ]
   },
   "language" : "perl",
   "notifications" : {
      "email" : [
         "wakaba@suikawiki.org"
      ],
      "irc" : {
         "channels" : [
            "ircs://irc.suikawiki.org:6697#mechanize"
         ],
         "use_notice" : true
      }
   },
   "perl" : [
      "5.26"
   ],
   "script" : "make test"
}
